;; This logfile was generated automatically by `xindy'
;; at 24.04.2019  21:03:20
;; Indexstyle: "/var/folders/s8/sxbd0nh54lx7lsblrgqfc5940000gn/T/KsKTGYEGDm", Rawindex: "/var/folders/s8/sxbd0nh54lx7lsblrgqfc5940000gn/T/9NO5gsN8Ks", Output: "/Users/Ahmed/Google_Drive/Thesis_PhD/dessertation/.texpadtmp/dissertation_song.acr"


Building indexentry-tree:
Hierdepth of index is :TREE


Forming letter-groups:
